name: waratha
description: waratha - Islamic inheritance calculator
publish_to: 'none'
version: 1.0.0+3
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.12.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.68.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
